#!/bin/bash
DIRNAME=`dirname $0`
cd $DIRNAME

# Validation
[ -z "$EXTERNAL_CONF_SHIBBOLETH_AUTH_APP_PORT" ] && echo "Missing EXTERNAL_CONF_SHIBBOLETH_AUTH_APP_PORT" && exit 125
#EXTERNAL_CONF_FOGBOW_GUI_URL=
#EXTERNAL_CONF_SHIBBOLETH_AUTH_PRIVATE_KEY_NAME=
#EXTERNAL_CONF_AUTHENTICATION_SERVICE_PUBLIC_KEY_NAME=
#EXTERNAL_CONF_SHIBBOLETH_AUTH_MACHINE_IP=
#EXTERNAL_CONF_SSH_PRIVATE_KEY_NAME=

# -- Constants Start --
DEFAULT_NAME_TO_REPLACE_SHIB_HTTP_PORT="_shib_http_port_"
DEFAULT_NAME_TO_REPLACE_FOGBOW_GUI_URL="_fogbow_gui_url_"
DEFAULT_NAME_TO_REPLACE_SHIB_PRIVATE_KEY_PATH="_ship_private_key_path_"
DEFAULT_NAME_TO_REPLACE_AS_PUBLIC_KEY_PATH="_as_public_key_path_"
DEFAULT_NAME_TO_REPLACE_SERVICE_PROVIDER_MACHINE_IP="_service_provider_machine_ip_"
# -- Constants End --

FILES_CONF_DINAMIC_FOLDER='/home/ubuntu/files-conf-dinamic'
FILES_CONF_STATIC_FOLDER='/home/ubuntu/files-conf-static'
SHIBB_AUTH_APP_FOLDER='/home/ubuntu/shibboleth-authentication-application'
MAIN_SSH_PATH='/home/ubuntu/.ssh/'

SHIBBOLETH_AUTH_PRIVATE_KEY_PATH=$FILES_CONF_DINAMIC_FOLDER/$EXTERNAL_CONF_SHIBBOLETH_AUTH_PRIVATE_KEY_NAME
AUTHENTICATION_SERVICE_PUBLIC_KEY_PATH=$FILES_CONF_DINAMIC_FOLDER/$EXTERNAL_CONF_AUTHENTICATION_SERVICE_PUBLIC_KEY_NAME
SSH_PRIVATE_KEY_PATH=$FILES_CONF_DINAMIC_FOLDER/$EXTERNAL_CONF_SSH_PRIVATE_KEY_NAME

SHIBBOLETH_AUTHENTICATION_APPLICATION_CONF_NAME='shibboleth-authentication-application.conf'
cp $FILES_CONF_STATIC_FOLDER/SHIBBOLETH_AUTHENTICATION_APPLICATION_CONF_NAME $SHIBB_AUTH_APP_FOLDER
sed -i s/$DEFAULT_NAME_TO_REPLACE_SHIB_HTTP_PORT/$EXTERNAL_CONF_SHIBBOLETH_AUTH_APP_PORT/g $SHIBB_AUTH_APP_FOLDER/$SHIBBOLETH_AUTHENTICATION_APPLICATION_CONF_NAME
sed -i s,$SHIBBOLETH_AUTHENTICATION_APPLICATION_CONF_NAME,$EXTERNAL_CONF_FOGBOW_GUI_URL,g $SHIBB_AUTH_APP_FOLDER/$SHIBBOLETH_AUTHENTICATION_APPLICATION_CONF_NAME
sed -i s,$DEFAULT_NAME_TO_REPLACE_SHIB_PRIVATE_KEY_PATH,$SHIBBOLETH_AUTH_PRIVATE_KEY_PATH,g $SHIBB_AUTH_APP_FOLDER/$SHIBBOLETH_AUTHENTICATION_APPLICATION_CONF_NAME
sed -i s,$DEFAULT_NAME_TO_REPLACE_AS_PUBLIC_KEY_PATH,$AUTHENTICATION_SERVICE_PUBLIC_KEY_PATH,g $SHIBB_AUTH_APP_FOLDER/$SHIBBOLETH_AUTHENTICATION_APPLICATION_CONF_NAME
sed -i s/$DEFAULT_NAME_TO_REPLACE_SERVICE_PROVIDER_MACHINE_IP/$EXTERNAL_CONF_SHIBBOLETH_AUTH_MACHINE_IP/g $SHIBB_AUTH_APP_FOLDER/$SHIBBOLETH_AUTHENTICATION_APPLICATION_CONF_NAME

cp $FILES_CONF_STATIC_FOLDER/log4j.properties $SHIBB_AUTH_APP_FOLDER

bash $SHIBB_AUTH_APP_FOLDER/bin/start-shib-app.sh

cp $SSH_PRIVATE_KEY_PATH $MAIN_SSH_PATH

ssh ubuntu@shibboleth-authentication-application -L 80:localhost:80 -f -N
